### ISSUE TITLE
Bug: "RecordViewController STT not working"

### ISSUE THREAD

**Issue by chad0909** [haru-speak/haruSpeak_iOS#36]
## 버그 내용
 
현재 STT 가 적용이 안되고 있음. 녹음 후 사용자의 목소리가 들리지만 이는 화면에 text로 출력이 안되고 있음

## 재현 과정
 
1. Go to 'RecordViewController()'
2. Click on 'Record (RedButton)'
3. Speak some sentences
4. Pause
5. Listen to the sentences
6. Wait for the text -> not showing (ERROR)

## 우려 사항

본인 시뮬레이터에서만 적용이 안되는 것 일 수도 있어서 확인을 해봐야함.

## 환경(Desktop)

- OS: [iOS]
- Version [16.2]
 
## 환경(Mobile)

- Device: [iPhone 14 Pro]
- OS: [iOS 16.2]
 
## 기타
-

**Comment by chad0909** [comment]
내 컴퓨터에서도 해결되어서 close 진행하겠습니다

**Comment by Yeeun411** [comment]
어떻게 해결했어??

**Comment by chad0909** [comment]
시뮬레이터 껐다 키니깐 되더라 ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by Yeeun411** [comment]
ㅋㅋㅋㅋㅋㅋ이번엔 내꺼가 안됔ㅋㅋㅋㅋㅋㅋ 껐다가 켜볼게^^
