### ISSUE TITLE
Bug: "RecordViewController DeleteButton not working"

### ISSUE THREAD

**Issue by Yeeun411** [haru-speak/haruSpeak_iOS#48]
## 버그 내용
RecordViewController DeleteButton not working
터치가 안됨
 
## 재현 과정
 
1. Go to 'RecordViewController'
2. Click on 'RecordButton'
3. Click on 'pauseButton'
4. Click on 'deleteButton'
5. See error

## 우려 사항
버튼 위치가 노치 근처라 터치가 안되는 것 같음!
버튼 top 레이아웃을 내리니 작동

## 스크린샷 
 
![Simulator Screen Shot - iPhone 14 Pro - 2023-01-23 at 20 04 46](https://user-images.githubusercontent.com/95922668/214024828-06a836f9-e896-46aa-b324-9beff703c8f9.png)

**Comment by chad0909** [comment]
이거 위에 navigationbar가 있어서 위쪽 부분이 안눌리는 현상일 수 도 있어. (우리눈에는 안보이지만 투명하게 있는 느낌?)

1. 해당 ViewController에 가서
2. ViewdidLoad() 쪽에
3. self.navigationController?.navigationBar.isHidden = true;
4. 위에 코드 추가하면 작동 될거라고 예상함!

**Comment by Yeeun411** [comment]
와 오늘 하루종일 레이아웃만 만졌는데...... 감사합니다......
