### ISSUE TITLE
Feat: "Add FouthViewController for UserSetting"

### ISSUE THREAD

**Issue by chad0909** [haru-speak/haruSpeak_iOS#92]
## 기능 요청사항

사용자 설정 화면 네번째화면

## 요청 세부사항

- ThirdViewController 에서 오는 ViewController
- 다음 누르면 FifthViewController() 로 가게끔 구현

## 레퍼런스
<img width="160" alt="스크린샷 2023-01-26 오전 4 45 35" src="https://user-images.githubusercontent.com/108044639/214672445-54278545-04c2-4264-9bdb-79465cdedb09.png">

**Comment by chad0909** [comment]
<img width="177" alt="스크린샷 2023-01-26 오전 4 56 05" src="https://user-images.githubusercontent.com/108044639/214675230-c9b14f95-7564-4594-9b31-e257b1852bf6.png">

<img width="180" alt="스크린샷 2023-01-26 오전 4 56 18" src="https://user-images.githubusercontent.com/108044639/214675283-26020a64-f8c4-4469-b5ec-9b418cdb4543.png">

위쪽이랑 아래쪽은 그냥 내가 작성해놓은 Properties, addsubview, layout 복붙하고 내용물만 바꾸면 될거야.
여기서 Progressbar는 따로 View쪽에만들어 놔서 이 ViewController viewdidload 에 

"self.progressBar.ratio = 4/5"

만 추가하면 4번 째 ViewController에 맞는 progress가 나올거임!

**Comment by Yeeun411** [comment]
5시에 일어난거야 5시에 잔거야..? 고마워~~ 이따 다 만들게!!
